// Auto-generated entity names from the scene


/**
 * Object containing all entity names in the scene for autocomplete support.
 */
export enum EntityNames {
  Bar_1_2M = "Bar 1 2M",
  Bar_1_2M_2 = "Bar 1 2M_2",
  Bar_1_2M_3 = "Bar 1 2M_3",
  Bar_2_3M = "Bar 2 3M",
  Bar_4_2M = "Bar 4 2M",
  Cactus_1 = "Cactus 1",
  Cactus_2 = "Cactus 2",
  Cart_Big_Closed = "Cart Big Closed",
  Druid_Wooden_Round_Table = "Druid Wooden Round Table",
  Elixir_2 = "Elixir_2",
  Fruit_1 = "Fruit 1",
  Grabbable_Axe = "Grabbable Axe",
  Grabbable_Axe_2 = "Grabbable Axe_2",
  Grog_Mug = "Grog Mug",
  Grog_Mug_2 = "Grog Mug_2",
  Grog_Mug_2_3 = "Grog Mug_2_3",
  Ground = "Ground",
  House_7_M_Train_Station = "House 7 M Train Station",
  House_7_M_Yellow = "House 7 M Yellow",
  House_8_M_Green = "House 8 M Green",
  Ladder = "Ladder",
  Light_Ref = "Light Ref",
  Light_Ref_2 = "Light Ref_2",
  Light_Ref_2_3 = "Light Ref_2_3",
  Message_In_A_Bottle = "Message In A Bottle",
  Peak = "Peak",
  Piano = "Piano",
  Piano_stool = "Piano stool",
  Plant_1 = "Plant 1",
  Stone_2 = "Stone 2",
  Stone_3 = "Stone 3",
  Stone_3_2 = "Stone 3_2",
  Stone_7 = "Stone 7",
  Tile_1 = "Tile 1",
  Tile_2 = "Tile 2",
  Tile_3 = "Tile 3",
  Tile_4 = "Tile 4",
  Tile_5 = "Tile 5",
  Tile_6 = "Tile 6",
  Tile_7 = "Tile 7",
  Tile_8 = "Tile 8",
  Tile_9 = "Tile 9",
  Train_Machine = "Train Machine",
  Train_Track_6_M_Old_V01 = "Train Track 6 M Old V01",
  Train_Track_6_M_Old_V01_2 = "Train Track 6 M Old V01_2",
  Train_Track_6_M_Old_V01_2_3 = "Train Track 6 M Old V01_2_3",
  Train_Track_6_M_Old_V01_2_3_4 = "Train Track 6 M Old V01_2_3_4",
  Tree_3 = "Tree 3",
  Wine_Bottle = "Wine Bottle",
  wenmoon = "wenmoon",
  zombie = "zombie",
} 
